/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package poe.prog5121;


import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author lucam
 */
public class POEPROG5121 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
          
        Login login = new Login();
        message chatSystem = new message();
        
      //GET NAME + SURNAME
       
      String name = JOptionPane.showInputDialog("Enter your name:");
      String surname = JOptionPane.showInputDialog("Enter your second name");
      
     // GET USERNAME + USERNAME DETAILS 
      
      String uName = JOptionPane.showInputDialog(
              "Your username should be formatted the following way: "
                      + "\n > Contains an underscore "
                      + "\n > maximum of 5 characters "
                      + "\n > Please enter your Username:" );
      
     // GET PASSWORD + PASSWORD DETAILS 
      
      String pWord = JOptionPane.showInputDialog(
              "Your password should be formatted in the following way"
              + " \n > Miniumum of 8 characters "
              + "\n > Contains a nukber "
              + "\n > conatains a capital letter "
              + "\n > contains a special character "
              + "\n > Please enter your password ");
      
     //GET PHONE NUMBER
      
     // Based on code generated by ChatGPT (OpenAI), modified by me (line 54 -75)
      
       JPanel panel = new JPanel();
       panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS)); 
      JLabel prompt = new JLabel("Please enter your South African phone number:");
      JPanel inputRow = new JPanel(); 
      JLabel label = new JLabel("+27");
      JTextField textField = new JTextField(10);
      inputRow.add(label);
      inputRow.add(textField);
      panel.add(prompt);     
      panel.add(inputRow);   
      int result = JOptionPane.showConfirmDialog(null, panel, 
          "Phone Number", JOptionPane.OK_CANCEL_OPTION);
    
      String fullPhoneNumber = ""; 
          if (result == JOptionPane.OK_OPTION) {
              String userInput = textField.getText();
              fullPhoneNumber = "+27" + userInput;
      
    }
          
     //CALL METHODS 
        boolean isUsernameValid = login.checkUserName(uName);
        boolean isPasswordValid = login.checkPasswordComplexity(pWord);
        boolean isCellValid = login.checkCellPhoneNumber(fullPhoneNumber);
        
        
        String results = login.registerUser(isUsernameValid, isPasswordValid, isCellValid);
        
        JOptionPane.showMessageDialog(null, results);
        
        boolean logged = false;
        
           if (results.equals("Registration successful")) {
            boolean loginSuccessful = login.loginUser(uName, pWord, results);
            
            if (loginSuccessful) {
                logged = true;
                // Start the chat application if login is successful
                chatSystem.startChatApplication(name, surname);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please register successfully before accessing the chat system.");
        }
        
        //goodbye message
        JOptionPane.showMessageDialog(null, "Thank you for using the Chat Platform, " + name + "!");
    }
}
    
    

